### ISSUE TITLE
Seems error in code.

### ISSUE THREAD

**Issue by CyberS4murai** [robotshell/magicRecon#9]
![image](https://github.com/robotshell/magicRecon/assets/139550584/f48a52e1-fdd8-4a01-965e-f0e0d13c7a12)

**Comment by psychomad** [comment]
I got the same issue and 2 are the way to fix:

1) install all go tools by yourself and move in right place (if not automatic)
2) modify installing script to proper go install command.

The install script use a old way to install things

**Comment by robotshell** [comment]
The installation script has been modified to correct several bugs.
